package infrusture.mapper;

import infrusture.entity.TempData;
import infrusture.entity.TempDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TempDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_data
     *
     * @mbg.generated
     */
    long countByExample(TempDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_data
     *
     * @mbg.generated
     */
    int deleteByExample(TempDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_data
     *
     * @mbg.generated
     */
    int insert(TempData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_data
     *
     * @mbg.generated
     */
    int insertSelective(TempData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_data
     *
     * @mbg.generated
     */
    List<TempData> selectByExample(TempDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_data
     *
     * @mbg.generated
     */
    TempData selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TempData record, @Param("example") TempDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TempData record, @Param("example") TempDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TempData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TempData record);
}