spring:
  server:
    port: 8080
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6vcn3dsi88h996zbo.mysql.rds.aliyuncs.com:3306/storage?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: schemer
    password: schemer123**
mybatis:
  mapper-locations: classpath:mapper/*.xml
type: com.alibaba.druid.pool.DruidDataSource
